# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('submit', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=0)),
                ('root', models.BooleanField(default=False)),
                ('stat', models.TextField(default={'Accepted': 0, 'Compile Error': 0, 'Memory Limit Exceeded': 0, 'Output Limit Exceeded': 0, 'Presentation Error': 0, 'Runtime Error': 0, 'System Error': 0, 'Time Limit Exceeded': 0, 'Wrong Answer': 0})),
                ('ips', models.TextField(default=[])),
            ],
        ),
    ]
