# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='root',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='submit',
        ),
        migrations.AddField(
            model_name='user',
            name='participate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='usedpoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stat',
            field=models.TextField(default=''),
        ),
    ]
