# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0002_auto_20170906_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ips',
        ),
    ]
