# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import yonghu.models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0003_remove_user_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stat',
            field=models.TextField(default=yonghu.models.User.stat_default),
        ),
    ]
