# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0005_user_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint1', models.BooleanField(default=True)),
                ('hint2', models.BooleanField(default=True)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
