# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0006_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='content',
        ),
    ]
